# Generated by Django 3.1.7 on 2021-06-22 17:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Food_Type', models.CharField(choices=[('wheat', 'WHEAT'), ('rice', 'RICE'), ('jowar', 'JOWAR'), ('soyabean', 'SOYABEAN'), ('turdal', 'TUR_DAL')], max_length=100)),
                ('Capacity', models.IntegerField()),
                ('Location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Godown', models.CharField(max_length=200)),
                ('Food_Type', models.CharField(choices=[('wheat', 'WHEAT'), ('rice', 'RICE'), ('jowar', 'JOWAR'), ('soyabean', 'SOYABEAN'), ('turdal', 'TUR_DAL')], max_length=100)),
                ('Total_Capacity', models.IntegerField()),
                ('Filled', models.IntegerField()),
                ('Remaining', models.IntegerField()),
                ('City', models.CharField(max_length=200)),
                ('godown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Godowns.godown')),
            ],
        ),
    ]
